version: '3'
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    hostname: nginx
    networks:
      - blog
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./conf/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./conf/nginx/general/:/etc/nginx/general/"
      - "./conf/nginx/sites-enabled/:/etc/nginx/sites-enabled/"
      - "./datadir/logs/nginx/access.log:/var/log/nginx/blog.access.log"
      - "./datadir/logs/nginx/error.log:/var/log/nginx/blog.error.log"
    depends_on:
      - blog

  blog:
    image: ghost:alpine
    container_name: blog
    hostname: blog
    networks:
      - blog
    environment:
      url: http://blog.local
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: example
      database__connection__database: blog
    volumes:
      - "./datadir/blog:/var/lib/ghost/content"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: db
    hostname: db
    networks:
      - blog
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - blog_data:/var/lib/mysql

volumes:
  blog_data: {}
networks:
  blog: